# Generated by Django 5.0.14 on 2026-03-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voter_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='voter',
            name='apart_num',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_register',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='precinct_number',
            field=models.CharField(max_length=10),
        ),
    ]
