# Generated by Django 5.0.14 on 2026-03-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_voter_voter_id_alter_voter_apart_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='apart_num',
            new_name='apartment_num',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='date_birth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='date_register',
            new_name='date_of_registration',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='voter_id',
        ),
        migrations.AlterField(
            model_name='voter',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
