# Generated by Django 5.0.14 on 2026-03-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0008_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
