from django.urls import path

from .views import (
    ApproveHouseholdJoinRequestView,
    ChoreCreateView,
    ChoreDetailView,
    ChoreListView,
    ExpenseCreateView,
    ExpenseDetailView,
    ExpenseListView,
    ExpenseShareCreateView,
    ExpenseShareDetailView,
    HouseholdCreateView,
    HouseholdDetailView,
    JoinHouseholdView,
    LeaveHouseholdView,
    MarkExpenseSharePaidView,
    MarkChoreCompletedView,
    MessageCommentCreateView,
    MessageCreateView,
    MessageDetailView,
    MessageListView,
    MyExpenseShareListView,
    ProjectHomeView,
    ProjectLoginView,
    ProjectLogoutView,
    RegisterUserView,
    TransferHouseholdManagerView,
    WhoOwesMeListView,
)

urlpatterns = [
    path("", ProjectHomeView.as_view(), name="project_home"),
    path("login/", ProjectLoginView.as_view(), name="project_login"),
    path("logout/", ProjectLogoutView.as_view(), name="project_logout"),
    path("register/", RegisterUserView.as_view(), name="project_register"),
    path("households/create/", HouseholdCreateView.as_view(), name="project_household_create"),
    path("households/<int:pk>/", HouseholdDetailView.as_view(), name="project_household_detail"),
    path("households/join/", JoinHouseholdView.as_view(), name="project_join_household"),
    path("households/leave/", LeaveHouseholdView.as_view(), name="project_leave_household"),
    path("households/join-requests/<int:pk>/approve/", ApproveHouseholdJoinRequestView.as_view(), name="project_household_join_request_approve"),
    path("households/<int:pk>/transfer-manager/", TransferHouseholdManagerView.as_view(), name="project_household_transfer_manager"),
    path("expenses/", ExpenseListView.as_view(), name="project_expense_list"),
    path("my-expenseshares/", MyExpenseShareListView.as_view(), name="project_my_expense_shares"),
    path("who-owes-me/", WhoOwesMeListView.as_view(), name="project_who_owes_me"),
    path("expenses/create/", ExpenseCreateView.as_view(), name="project_expense_create"),
    path("expenses/<int:pk>/", ExpenseDetailView.as_view(), name="project_expense_detail"),
    path("expenses/<int:pk>/shares/create/", ExpenseShareCreateView.as_view(), name="project_expense_share_create"),
    path("expense-shares/<int:pk>/", ExpenseShareDetailView.as_view(), name="project_expense_share_detail"),
    path("expense-shares/<int:pk>/mark-paid/", MarkExpenseSharePaidView.as_view(), name="project_expense_share_mark_paid"),
    path("chores/", ChoreListView.as_view(), name="project_chore_list"),
    path("chores/create/", ChoreCreateView.as_view(), name="project_chore_create"),
    path("chores/<int:pk>/", ChoreDetailView.as_view(), name="project_chore_detail"),
    path("chores/<int:pk>/complete/", MarkChoreCompletedView.as_view(), name="project_chore_complete"),
    path("messages/", MessageListView.as_view(), name="project_message_list"),
    path("messages/create/", MessageCreateView.as_view(), name="project_message_create"),
    path("messages/<int:pk>/", MessageDetailView.as_view(), name="project_message_detail"),
    path("messages/<int:pk>/comments/create/", MessageCommentCreateView.as_view(), name="project_message_comment_create"),
]
