# Generated by Django 5.0.14 on 2026-04-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_message_messagecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenseshare',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
